/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProviderRouteImport } from './routes/provider'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProviderIndexRouteImport } from './routes/provider.index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as ProviderSharedRouteImport } from './routes/provider.shared'
import { Route as ProviderHistoryRouteImport } from './routes/provider.history'
import { Route as ProviderCodeRouteImport } from './routes/provider.code'
import { Route as AppShareRouteImport } from './routes/app.share'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppRequestsRouteImport } from './routes/app.requests'
import { Route as AppLogsRouteImport } from './routes/app.logs'
import { Route as AppHospitalsRouteImport } from './routes/app.hospitals'
import { Route as AppDocumentsRouteImport } from './routes/app.documents'
import { Route as AppAssistantRouteImport } from './routes/app.assistant'

const ProviderRoute = ProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIndexRoute = ProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProviderRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ProviderSharedRoute = ProviderSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderHistoryRoute = ProviderHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ProviderRoute,
} as any)
const ProviderCodeRoute = ProviderCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => ProviderRoute,
} as any)
const AppShareRoute = AppShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppRequestsRoute = AppRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AppRoute,
} as any)
const AppLogsRoute = AppLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AppRoute,
} as any)
const AppHospitalsRoute = AppHospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentsRoute = AppDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/provider': typeof ProviderRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/hospitals': typeof AppHospitalsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/share': typeof AppShareRoute
  '/provider/code': typeof ProviderCodeRoute
  '/provider/history': typeof ProviderHistoryRoute
  '/provider/shared': typeof ProviderSharedRoute
  '/app/': typeof AppIndexRoute
  '/provider/': typeof ProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/assistant': typeof AppAssistantRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/hospitals': typeof AppHospitalsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/share': typeof AppShareRoute
  '/provider/code': typeof ProviderCodeRoute
  '/provider/history': typeof ProviderHistoryRoute
  '/provider/shared': typeof ProviderSharedRoute
  '/app': typeof AppIndexRoute
  '/provider': typeof ProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/provider': typeof ProviderRouteWithChildren
  '/app/assistant': typeof AppAssistantRoute
  '/app/documents': typeof AppDocumentsRoute
  '/app/hospitals': typeof AppHospitalsRoute
  '/app/logs': typeof AppLogsRoute
  '/app/requests': typeof AppRequestsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/share': typeof AppShareRoute
  '/provider/code': typeof ProviderCodeRoute
  '/provider/history': typeof ProviderHistoryRoute
  '/provider/shared': typeof ProviderSharedRoute
  '/app/': typeof AppIndexRoute
  '/provider/': typeof ProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/provider'
    | '/app/assistant'
    | '/app/documents'
    | '/app/hospitals'
    | '/app/logs'
    | '/app/requests'
    | '/app/settings'
    | '/app/share'
    | '/provider/code'
    | '/provider/history'
    | '/provider/shared'
    | '/app/'
    | '/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/assistant'
    | '/app/documents'
    | '/app/hospitals'
    | '/app/logs'
    | '/app/requests'
    | '/app/settings'
    | '/app/share'
    | '/provider/code'
    | '/provider/history'
    | '/provider/shared'
    | '/app'
    | '/provider'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/provider'
    | '/app/assistant'
    | '/app/documents'
    | '/app/hospitals'
    | '/app/logs'
    | '/app/requests'
    | '/app/settings'
    | '/app/share'
    | '/provider/code'
    | '/provider/history'
    | '/provider/shared'
    | '/app/'
    | '/provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  ProviderRoute: typeof ProviderRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/provider': {
      id: '/provider'
      path: '/provider'
      fullPath: '/provider'
      preLoaderRoute: typeof ProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/': {
      id: '/provider/'
      path: '/'
      fullPath: '/provider/'
      preLoaderRoute: typeof ProviderIndexRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/provider/shared': {
      id: '/provider/shared'
      path: '/shared'
      fullPath: '/provider/shared'
      preLoaderRoute: typeof ProviderSharedRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/history': {
      id: '/provider/history'
      path: '/history'
      fullPath: '/provider/history'
      preLoaderRoute: typeof ProviderHistoryRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/provider/code': {
      id: '/provider/code'
      path: '/code'
      fullPath: '/provider/code'
      preLoaderRoute: typeof ProviderCodeRouteImport
      parentRoute: typeof ProviderRoute
    }
    '/app/share': {
      id: '/app/share'
      path: '/share'
      fullPath: '/app/share'
      preLoaderRoute: typeof AppShareRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/requests': {
      id: '/app/requests'
      path: '/requests'
      fullPath: '/app/requests'
      preLoaderRoute: typeof AppRequestsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/logs': {
      id: '/app/logs'
      path: '/logs'
      fullPath: '/app/logs'
      preLoaderRoute: typeof AppLogsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/hospitals': {
      id: '/app/hospitals'
      path: '/hospitals'
      fullPath: '/app/hospitals'
      preLoaderRoute: typeof AppHospitalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documents': {
      id: '/app/documents'
      path: '/documents'
      fullPath: '/app/documents'
      preLoaderRoute: typeof AppDocumentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/assistant': {
      id: '/app/assistant'
      path: '/assistant'
      fullPath: '/app/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssistantRoute: typeof AppAssistantRoute
  AppDocumentsRoute: typeof AppDocumentsRoute
  AppHospitalsRoute: typeof AppHospitalsRoute
  AppLogsRoute: typeof AppLogsRoute
  AppRequestsRoute: typeof AppRequestsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppShareRoute: typeof AppShareRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssistantRoute: AppAssistantRoute,
  AppDocumentsRoute: AppDocumentsRoute,
  AppHospitalsRoute: AppHospitalsRoute,
  AppLogsRoute: AppLogsRoute,
  AppRequestsRoute: AppRequestsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppShareRoute: AppShareRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface ProviderRouteChildren {
  ProviderCodeRoute: typeof ProviderCodeRoute
  ProviderHistoryRoute: typeof ProviderHistoryRoute
  ProviderSharedRoute: typeof ProviderSharedRoute
  ProviderIndexRoute: typeof ProviderIndexRoute
}

const ProviderRouteChildren: ProviderRouteChildren = {
  ProviderCodeRoute: ProviderCodeRoute,
  ProviderHistoryRoute: ProviderHistoryRoute,
  ProviderSharedRoute: ProviderSharedRoute,
  ProviderIndexRoute: ProviderIndexRoute,
}

const ProviderRouteWithChildren = ProviderRoute._addFileChildren(
  ProviderRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  ProviderRoute: ProviderRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
